name: "KiCad CI/CD for Host"

on:
  schedule:
    - cron: "0 8 * * 1"
  workflow_dispatch:
  pull_request:
    paths:
      - 'Hardware/Pico_PMod/*.kicad_sch'
      - 'Hardware/Pico_PMod/*.kicad_pcb'
      - 'Hardware/kibot.yml'
      - '.github/workflows/Pico_Pmod_kicad.yml'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  Fabrication:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: INTI-CMNB/KiBot@v2_k7
      with:
        # Required - kibot config file
        config: Hardware/kibot.yml
        # optional - prefix to output defined in config
        dir: Hardware/Fabrication
        # optional - schematic file
        schema: 'Hardware/Pico_PMod/pico_pmod_host.kicad_sch'
        # optional - PCB design file
        board: 'Hardware/Pico_PMod/pico_pmod_host.kicad_pcb'

    - name: Retrieve results
      if: ${{ always() }}
      uses: actions/upload-artifact@v4
      with:
        name: Fabrication_Files
        path: |
          Hardware/Fabrication/
        if-no-files-found: warn
